### PR TITLE
Specify 2021-06-02 as the API version to use, update logs command for new structure

### PR DESCRIPTION
**Pull request by robbieaverill**
Follow on from https://github.com/chec/cli/pull/45

### CODE REVIEW

**Review by ScopeyNZ — APPROVED** [review]
Code LGTM. There's some test stubs that may need updating

**Comment by robbieaverill** [comment]
The only issue with this approach is that the logs command will now be broken for all of our existing CLI users, until they upgrade.

**Comment by ScopeyNZ** [comment]
Only if they don't already have old keys (with an old API version) issued though right?

**Comment by robbieaverill** [comment]
Yeah, it'd only be users who have downloaded the CLI but never used it that would be affected. Probably unlikely.

**Pull request merged**
