### PR TITLE
Update logs command to handle breaking pagination changes in "list logs" API

### PR DESCRIPTION
**Pull request by robbieaverill**
Version 2021-06-02 will introduce breaking changes to the API that this command consumes, so this patch updates to handle it.

### CODE REVIEW

**Comment by ScopeyNZ** [comment]
We really should have updated this a while ago to specify a version in the request headers so it won't immediately break for people without updating. Can you specify the new version in the request for this PR please?

**Comment by robbieaverill** [comment]
> Can you specify the new version in the request for this PR please?

New API keys will use the latest version, and older API keys will use the old version. I went for a simple "use the data key if it's there" approach instead of baking specific API key versions in. Happy to change if you don't like that approach though.

**Review by kvisca — APPROVED** [review]
The code looks fine to me, I'll let you two decide if you want to go @ScopeyNZ  suggestion. If no, merge away!

**Comment by ScopeyNZ** [comment]
I think we should specify `2021-06-02` in the request as we're relying on specifically that version for this to work properly.

**Comment by robbieaverill** [comment]
It makes sense to specify a version, I've raised a PR for that at #46

**Pull request closed without merging**
